#!/usr/bin/python
import sys
import subprocess

def execute(cmd):
    try:
        subprocess.run(cmd, shell=True, check=True)
    except subprocess.CalledProcessError as e:
        print(f"Command failed with exit code {e.returncode}")

modules = ["monitor", "reader", "web"]
extra_args = ""

if len(sys.argv) < 2:
    module = "monitor"
else:
    module = sys.argv[1]

if module not in modules:
    print("Please select a valid module:\n" \
    "[1] monitor (default)\n" \
    "[2] reader\n" \
    "[3] web\n")
    sys.exit()

if len(sys.argv) > 2:
    extra_args += " " + " ".join(sys.argv[2::])

print(extra_args)

execute(f"python {module}.py {extra_args}")